### PR TITLE
chore: Additional setup requirements for Windows users

### PR DESCRIPTION
**Pull request by TERR-inss**
Including some basic steps that were required to run Docker, and therefore the application generally, on my Windows machine.

### CODE REVIEW

**Comment by peterklingelhofer** [comment]
Hey @TERR-inss, thanks so much for this! Looks like your commit failed our commitlint stage (basically you prefix your commit messages with 'chore: ' or 'fix: ' or 'cleanup: ', 'chore: ' is probably most appropriate for this one).

You can modify pushed commits via command line or with a client like [SmartGit](https://www.syntevo.com/smartgit/). Thanks so much for this PR, it's great to have you around!

**Comment by TERR-inss** [comment]
Thanks for the warm welcome @peterklingelhofer !

I made the mistake of writing this commit directly on a fork in the browser which gave it a weird two line commit message, but now I've updated the commit message to begin with chore: and updated the branch, so hopefully this will do it.

**Comment by peterklingelhofer** [comment]
Hey @TERR-inss, 

Ah I see now. Yeah might be best to just close and open a fresh one! And yeah the commit messages can be silly, I definitely failed that test on many of my early contributions because I kept forgetting about it. 😜

**Comment by simonv3** [comment]
For what it's worth I don't think the commit lint error is worth the hassle of doing more work, just a heads up for the future.

**Review by simonv3 — APPROVED** [review]

**Comment by TERR-inss** [comment]
Ohh I see you just merged the one commit - awesome! Yup i had thought the commit lint error was a full-on blocker. Thanks for approving and moving it into main.

**Pull request merged**
