### PR TITLE
Issue 172: File Upload test data

### PR DESCRIPTION
**Pull request by mattburnett-repo**
this PR is an update to 698829cc87978441471295dee64dee6fb4b810ee.

It deletes file used to generate the test data, un-needed test audio files, and references to how the test data was created.

### CODE REVIEW

**Review by simonv3 — CHANGES_REQUESTED** [review]
It looks like fixing the test would just be a matter of changing the number 1 to 31 (cause there's now 31 files!)

**Comment by mattburnett-repo** [comment]
> 

There's more to it. Here from a previous test run:

3 failing

  1) user/admin/files endpoint test
       Authorized
         should GET /user/admin/files:

      AssertionError: expected 31 to deeply equal 1
      + expected - actual

      -31
      +1
      
      at Context.<anonymous> (test/baseline/admin/Files.test.js:55:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) baseline/admin/trackgroups endpoint test
       Admin Trackgroups
         should get trackgroup by id:
     AssertionError: expected { …(2) } to be null
      at Context.<anonymous> (test/baseline/admin/Trackgroups.test.js:131:39)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  3) baseline/artists endpoint test
       should GET /artists:
     AssertionError: expected 'b60f1759-6405-[445](https://github.com/resonatecoop/api/actions/runs/3855517239/jobs/6570650921#step:10:446)7-9910-6da1ccd5f40f' to be null
      at Context.<anonymous> (test/baseline/artists/Artists.test.js:94:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by simonv3** [comment]
@mattburnett-repo those still seem like pretty quick fixes no?

failing test 2:

      expect(theTrack.audiofile).to.be.null

it makes sense that's not null anymore. 

failing test 3:

    expect(theTrack.url).to.be.null

this would also not be null anymore.

**Comment by mattburnett-repo** [comment]
> @mattburnett-repo those still seem like pretty quick fixes no?
> 
> failing test 2:
> 
> ```
>   expect(theTrack.audiofile).to.be.null
> ```
> 
> it makes sense that's not null anymore.
> 
> failing test 3:
> 
> ```
> expect(theTrack.url).to.be.null
> ```
> 
> this would also not be null anymore.

I get it. I really do.

I've been staring at this thing for about a month now, and it's time to bring it to a close.

The code in this PR addresses the problem in issue 172. It's done, and needs to be merged with the codebase. Once that's done, I can pull a clean copy of the repo and fix the broken tests. I don't know what to expect, but am hopeful that it won't take too long or be too ugly. There's more to it than just changing a few values.

Do whatever you want with that.

**Review by simonv3 — APPROVED** [review]

**Pull request merged**
